### ISSUE TITLE
Donor profile solution

### ISSUE THREAD

**Issue by samanthashain** [samanthashain/Conga-Composer-for-Nonprofits#25]
As a Fundraiser, I need to download a PDF of a donor or household (TBD), including related information such as recent + open tasks/activities, recent gifts, fundraising metrics, campaign membership, etc.

- [ ] Solution should include SOQL statements, recommended parameters, and template(s)
- [ ] Template design with nice, table-based layout?

**Comment by samanthashain** [comment]
From S.M. " We really want to be able to pull in any data we have on Salesforce related to a particular employer partner [Organization record], and generate a document that staff members can use to prep themselves for meetings with these partner organizations - surfacing Opportunity, Activity, and other related data in an easy to comprehend summary sheet."

**Comment by samanthashain** [comment]
[OrgProfile - Boogle (8).docx](https://github.com/samanthashain/Conga-Composer-for-Nonprofits/files/7555983/OrgProfile.-.Boogle.8.docx)
 Here's a mockup that I merged with "real" org data (including logo)

**Comment by JustinBarss** [comment]
@samanthashain Yes - Apsona can do Donor Profile sheets like this in the same fashion.  If there's a partner interested in this - please send them to Partner Hours (Tuesdays at 3pm ET/ 12pm PT) - schedule is available here:  http://bit.ly/ApsonaTrailblazers

We would use your same template of a single document with multiple TableStart: / TableEnd: merge tags that represent child records you want to include from the object referenced as "Boogle"

We use the term "Top Level" to refer to the record you've identifed as "Boogle" - presumably an Account Record.
Then there would be "Sub Lists" representing various records that are related to Boogle.  These could be child records with a lookup field from Child to Parent (Boogle) - or linked in a different way (i.e. a custom report that is linked to Boogle somehow of non-lookup linkages).
https://apsona.com/pages/sfdc/doc/doc-merge-with-sublists.html
Happy to chat more if anyone needs assistance!
Partners - join us at Partner Hours on Tuesdays
Everyone else - join us for Apsona Hours on Thursdays at 1pm ET/ 10am PT!
